name: Check Python Code Style with Style50

on: [push, pull_request]

jobs:
  style50:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install style50

    - name: Run Style50
      run: |
        style50 /workspaces/Portfolio.-C-language/Python/practice/simple_calculator.py